# -----------------------------------------------------------------------------
# OUTPUTS - Azure AD Resources
# -----------------------------------------------------------------------------

output "group_object_id" {
  description = "The object ID of the Azure AD security group for privileged access"
  value       = azuread_group.privileged_access.object_id
}

output "group_name" {
  description = "The display name of the Azure AD security group"
  value       = azuread_group.privileged_access.display_name
}

output "application_id" {
  description = "The application (client) ID of the Azure AD application"
  value       = azuread_application.uaa_saml.client_id
}

output "application_object_id" {
  description = "The object ID of the Azure AD application"
  value       = azuread_application.uaa_saml.object_id
}

output "service_principal_id" {
  description = "The object ID of the service principal (enterprise application)"
  value       = azuread_service_principal.uaa_saml.object_id
}

output "tenant_id" {
  description = "The Azure AD tenant ID"
  value       = local.tenant_id
}

# -----------------------------------------------------------------------------
# OUTPUTS - SAML Configuration
# -----------------------------------------------------------------------------

output "saml_metadata_url" {
  description = "The URL to fetch SAML federation metadata from Azure AD. Use this in UAA if you prefer URL-based metadata."
  value       = local.saml_metadata_url
}

output "saml_entity_id" {
  description = "The SAML Entity ID (Issuer) of Azure AD. UAA uses this to verify SAML assertions."
  value       = local.saml_entity_id
}

output "saml_sso_url" {
  description = "The SAML Single Sign-On URL where UAA should redirect users for authentication"
  value       = local.saml_sso_url
}

output "saml_logout_url" {
  description = "The SAML Single Logout URL for sign-out"
  value       = local.saml_logout_url
}

output "saml_certificate_thumbprint" {
  description = "The thumbprint of the SAML signing certificate"
  value       = azuread_service_principal_token_signing_certificate.uaa_saml.thumbprint
}

output "saml_certificate_pem" {
  description = "The SAML signing certificate in PEM format. Include this in UAA configuration if not using metadata URL."
  value       = azuread_service_principal_token_signing_certificate.uaa_saml.value
  sensitive   = true
}

output "saml_certificate_key_id" {
  description = "The key ID of the SAML signing certificate"
  value       = azuread_service_principal_token_signing_certificate.uaa_saml.key_id
}

# -----------------------------------------------------------------------------
# OUTPUTS - App Roles
# -----------------------------------------------------------------------------

output "app_role_values" {
  description = "List of app role values that will be included in SAML assertions. Map these to UAA scopes."
  value       = [for role in var.app_roles : role.value]
}

output "app_role_ids" {
  description = "Map of app role values to their Azure AD object IDs"
  value       = local.app_role_ids
}

# -----------------------------------------------------------------------------
# OUTPUTS - PIM Configuration
# -----------------------------------------------------------------------------

output "pim_policy_id" {
  description = "The ID of the PIM policy for the group (member scope)"
  value       = local.policy_id_member
}

output "pim_eligible_member_ids" {
  description = "List of user object IDs that are eligible for group membership"
  value       = var.eligible_member_ids
}

output "pim_settings" {
  description = "Summary of PIM configuration settings"
  value = {
    max_activation_hours    = var.pim_max_activation_hours
    require_mfa             = var.pim_require_mfa
    require_justification   = var.pim_require_justification
    require_approval        = var.pim_require_approval
    eligibility_permanent   = var.pim_eligibility_permanent
    send_notifications      = var.pim_send_notifications
  }
}

# -----------------------------------------------------------------------------
# OUTPUTS - UAA Configuration
# -----------------------------------------------------------------------------

output "uaa_saml_provider_config" {
  description = "Complete UAA SAML provider configuration in YAML format. Add this to your UAA manifest under login.saml.providers."
  sensitive   = true
  value       = <<-EOT
# =============================================================================
# UAA SAML Provider Configuration
# =============================================================================
# Add this to your UAA manifest under login.saml.providers
# 
# Generated by Terraform for: ${var.application_name}
# Azure AD Tenant: ${local.tenant_id}
# Group: ${var.group_name}
# =============================================================================

login:
  saml:
    providers:
      azure-${replace(lower(var.group_name), "/[^a-z0-9]/", "-")}:
        # Azure AD SAML Metadata URL
        # Option 1: Use metadata URL (recommended - auto-updates on certificate rotation)
        idpMetadata: ${local.saml_metadata_url}
        
        # Option 2: Use inline metadata (uncomment and paste metadata XML)
        # idpMetadata: |
        #   <EntityDescriptor>...</EntityDescriptor>
        
        # Name ID format
        nameID: urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress
        
        # Assertion consumer service index
        assertionConsumerIndex: 0
        
        # Verify metadata signature
        metadataTrustCheck: true
        
        # Show login link on UAA login page
        showSamlLoginLink: true
        linkText: "Login with Azure AD (${var.group_name})"
        
        # Optional: Azure AD logo
        # iconUrl: "https://docs.microsoft.com/azure/media/index/azure-active-directory.svg"
        
        # Attribute mappings - map SAML claims to UAA attributes
        attributeMappings:
          # Map Azure AD claims to UAA user attributes
          given_name: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname
          family_name: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname
          email: http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress
          
          # Map the 'roles' claim to external groups
          # This is where app roles from Azure AD are passed to UAA
          external_groups:
            - http://schemas.microsoft.com/ws/2008/06/identity/claims/role
        
        # Whitelist of external groups (app roles) that UAA should accept
        externalGroupsWhitelist:
%{for role in var.app_roles~}
          - ${role.value}
%{endfor~}

# =============================================================================
# External Group Mappings
# =============================================================================
# Add this to your UAA configuration to map Azure AD app roles to UAA scopes
#
# These mappings connect:
#   Azure AD App Role -> UAA Group (scope)
# =============================================================================

uaa:
  scim:
    external_groups:
      # Origin must match the provider alias above
      azure-${replace(lower(var.group_name), "/[^a-z0-9]/", "-")}:
%{for role in var.app_roles~}
        # ${role.display_name}: ${role.description}
        ${role.value}:
          - ${replace(role.value, "-", ".")}
%{endfor~}

# =============================================================================
# Example Usage Notes
# =============================================================================
#
# 1. PIM Activation:
#    - Users go to https://portal.azure.com -> PIM -> My Roles -> Groups
#    - Find "${var.group_name}" and click "Activate"
#    - Complete MFA and provide justification
#    - Wait for peer approval (another group member must approve)
#    - Once approved, user has ${var.pim_max_activation_hours} hours of access
#
# 2. Login Flow:
#    - User accesses CredHub/CF and is redirected to UAA
#    - User clicks "Login with Azure AD (${var.group_name})"
#    - User authenticates with Azure AD
#    - Azure AD issues SAML assertion with app roles (if PIM is active)
#    - UAA maps app roles to scopes
#    - User receives token with appropriate scopes
#
# 3. App Roles to Scope Mapping:
%{for role in var.app_roles~}
#    - ${role.value} -> ${replace(role.value, "-", ".")}
%{endfor~}
#
# =============================================================================
EOT
}

# -----------------------------------------------------------------------------
# OUTPUTS - Quick Reference
# -----------------------------------------------------------------------------

output "quick_reference" {
  description = "Quick reference for the most commonly needed values"
  value = {
    # Azure AD identifiers
    tenant_id            = local.tenant_id
    application_id       = azuread_application.uaa_saml.client_id
    group_object_id      = azuread_group.privileged_access.object_id
    
    # SAML endpoints
    saml_metadata_url    = local.saml_metadata_url
    saml_sso_url         = local.saml_sso_url
    saml_entity_id       = local.saml_entity_id
    
    # For UAA external group mapping
    app_roles_to_map     = [for role in var.app_roles : {
      external_group = role.value
      uaa_scope      = replace(role.value, "-", ".")
    }]
    
    # PIM portal URL for activation
    pim_activation_url   = "https://portal.azure.com/#view/Microsoft_Azure_PIMCommon/ActivationMenuBlade/~/aadgroup"
  }
}
